# Generated by Django 5.2.7 on 2025-11-12 17:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_category_alter_education_current_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeproject',
            options={},
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resumeproject',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='resumeproject',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
    ]
