# Generated by Django 5.2.7 on 2025-11-05 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_skill_category_alter_education_current_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeproject',
            options={},
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resumeproject',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='resumeproject',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
    ]
