# Generated by Django 5.2.7 on 2025-11-24 15:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_resumeproject_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioproject',
            old_name='github_link',
            new_name='github_client',
        ),
        migrations.RenameField(
            model_name='resumeproject',
            old_name='github_url',
            new_name='github_client',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='github_server',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeproject',
            name='github_server',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
